# Generated by Django 4.2.7 on 2024-03-01 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=12)),
                ('company_name', models.CharField(max_length=40)),
                ('establish_year', models.IntegerField()),
                ('company_size', models.CharField(choices=[('1-25 employees', '1-25 employees'), ('26-50 employees', '26-50 employees'), ('51-100 employees', '51-100 employees'), ('100-500 employees', '100-500 employees'), ('500+ employees', '500+ employees')], max_length=17)),
                ('country', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('thana', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
