# Generated by Django 4.2.7 on 2024-03-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_industry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='thana',
        ),
    ]
