# Generated by Django 4.2.7 on 2024-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_remove_employer_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='designation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
