# Generated by Django 4.2.7 on 2024-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='typeo',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'offline')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
