# Generated by Django 4.2.7 on 2024-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_typeo_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='typeo',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=40, null=True),
        ),
    ]
