# Generated by Django 4.2.7 on 2024-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Part time', 'part_time'), ('Full time', 'full_time')], max_length=40),
        ),
    ]
