# Generated by Django 4.2.7 on 2024-03-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_alter_seeker_user_alter_seekerpersonal_user'),
        ('job', '0005_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='static/uploaded_cv/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekers.seeker')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
