# Generated by Django 4.2.7 on 2024-03-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_alter_seeker_user_alter_seekerpersonal_user'),
        ('job', '0006_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='seekers.seeker'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.job'),
        ),
    ]
